# Generated by Django 3.1.4 on 2020-12-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decklist_title', models.CharField(max_length=200)),
                ('decklist_format', models.CharField(max_length=200)),
                ('decklist_maindeck', models.TextField()),
                ('decklist_sideboard', models.TextField()),
                ('decklist_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
